### ISSUE TITLE
pixel experience

### ISSUE THREAD

**Issue by Fauxly** [xiaomi-unicorn/README#1]
Where can I get installation files? boot, rom

**Comment by kuailexs** [comment]
QQ群： 905034081
或者： https://mirrors.kuailexs.com/roms/xiaomi-12spro/PixelExperience_Plus_unicorn-13.0-20230929-1215-UNOFFICIAL.zip

**Comment by kuailexs** [comment]
> how to flash? and where is boot.img?

Install Guide
Download the ROM zip
Install a compatible Recovery
Perform an android backup of your current ROM (Optional)
Wipe data/factory reset
Flash PixelExperience Plus
Reboot

**Comment by kuailexs** [comment]
请问你是需要编译LineageOS么？

**Comment by Fauxly** [comment]
I have already compiled lineageos.  gapps are not installed.  most likely a problem with the partitions

**Comment by Fauxly** [comment]
what sources did you use to compile the kernel in PE?

**Comment by kuailexs** [comment]
The OSS kernel is not yet available

**Comment by kuailexs** [comment]
A lot of hardware drivers are missing

**Comment by Fauxly** [comment]
what is the release date of oss?  For PE, what sources did you use?

**Comment by Fauxly** [comment]
> The OSS kernel is not yet available

what is the release date of oss? For PE, what sources did you use?

**Comment by Fauxly** [comment]
https://drive.google.com/file/d/1_3Cu2ULRPs4EgZdMcV98hNlgH0wqbppU/view?usp=drive_link  LOS20

**Comment by kuailexs** [comment]
> LOS20 https://drive.google.com/file/d/1_3Cu2ULRPs4EgZdMcV98hNlgH0wqbppU/view?usp=drive_link

Can you share your fix code？

**Comment by Fauxly** [comment]
> Can you share your fix code？

https://github.com/Fauxly/android_device_xiaomi_unicorn/blob/5ad3892eb398843186666e501bb9b26e618402ed/rootdir/etc/init.target.rc#L621

**Comment by kuailexs** [comment]
> > Can you share your fix code？
> 
> https://github.com/Fauxly/android_device_xiaomi_unicorn/blob/5ad3892eb398843186666e501bb9b26e618402ed/rootdir/etc/init.target.rc#L612

Thank you very much
